MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/srv/beegfs02/scratch/visobt4s/data/detection/pre-trained-models/e2e_faster_R-50-FPN_1x.pkl"
  # WEIGHT: "/home/goutam/data/detection/checkpoints/iounet_ft_test4/model_final.pth"
  TRAIN_BBREG_ON: False
  TRAIN_RPN: False
  TRAIN_BACKBONE: False
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    FREEZE_CONV_BODY_AT: 4
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  IOU_PRED_ON: True
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    PERFORM_FILTERING: False
    POOLER_TYPE: "roi_align"
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_IOU_HEAD:
    PERFORM_FILTERING: True
    POOLER_TYPE: "prpool"
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "IoUNetPredictor"
    NUM_TRAIN_PROPOSALS: 32
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("coco_2014_minival",)
DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (1, 2)
  MAX_ITER: 3
OUTPUT_DIR: "/srv/beegfs02/scratch/visobt4s/data/detection/checkpoints/iounet_ft_test6"
